# tervis.ci.yml
version: 1

# Define the environment
env:
  name: ubuntu
  version: 20.04

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from your repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python environment
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    # Step 3: Install any necessary Python dependencies
    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt

    # Step 4: Make monster.py executable
    - name: Make monster.py executable
      run: chmod +x monster

    # Step 5: Run the monster.py Python script
    - name: Run monster.py
      run: python3 monster.py
